### ISSUE TITLE
support at-least-one groups of features (nested ideally)

### ISSUE THREAD

**Issue by rbtcollins** [frewsxcv/cargo-all-features#42]
In rustup we have two HTTP backends (curl and reqwest). These are both features, and both can be disabled, but at least one must be enabled.

Similarly, for reqwest we have two features selecting the TLS cert stack to use, and again at least one must be enabled.

We enable sensible defaults via the default-features mechanism.

So we have the following feature sets that are valid:
["curl-backend"]
["reqwest-backend", "reqwest-default-tls"]
["curl-backend", "reqwest-backend", "reqwest-default-tls"]
["reqwest-backend", "reqwest-rustls-tls"]
["curl-backend", "reqwest-backend", "reqwest-rustls-tls"]
["reqwest-backend", "reqwest-default-tls", "reqwest-default-tls"]
["curl-backend", "reqwest-backend", "reqwest-default-tls", "reqwest-default-tls"]

I'd love to be able to express this to cargo-all-features somehow. Right now I've just forced it to always have reqwest-backend and request-rustls-tls on.

**Comment by demmerichs** [comment]
I opened a PR #50 that would allow to give the following specification, resulting in your required feature sets:
```toml
[features]
curl-backend = []
reqwest-backend = []
reqwest-default-tls = ["reqwest-backend"]
reqwest-rustls-tls = ["reqwest-backend"]

[package.metadata.cargo-all-features]
rules = [
    "'curl-backend'|'reqwest-backend'",
    "'reqwest-backend'=>'reqwest-default-tls'|'reqwest-rustls-tls'",
]
```
Feel free to use the PR in the meantime, read the README for more details of this feature, and give feedback. I also added a [test case](https://github.com/frewsxcv/cargo-all-features/blob/5029f8f7ea34fa607e123920716bbe80d71b8739/tests/cli.rs#L379-L418) based off of this issue.
