### ISSUE TITLE
feature foo needs feature bar

### ISSUE THREAD

**Issue by LuckyTurtleDev** [frewsxcv/cargo-all-features#43]
I have a feature `foo` which required also feature `bar` to be enabled.
It looks like this can not be tested with cargo-all-feautures currently.

At the moment you can skip all combination of feature 
```toml
skip_feature_sets = [
    ["foo", "bar"],
]
```
But I can not do something like this: 
```toml
skip_feature_sets = [
    ["foo", "!bar"],
]
```
Alternative a new `deps` field can be added:
```toml
[[deps]]
  feature = "foo"
  needs = ["bar"]
```

**Comment by demmerichs** [comment]
I created now the PR #50, which would allow to specify this dependency only for the purpose of testing:
```toml
[package.metadata.cargo-all-features]
rules = [
    "bar => foo"
]
```
See README in that PR for more details on this feature.

**Comment by DidingasLushis** [comment]
Related to to this:

Q: How can we make it so there are feature paths?

- Currently
    - I always want my build to have feature X
        - doable with always include features
    - I want feature X to need feature Y 
        - X = ["Y"]
- My Confusion
    -  I want always X which needs Y, or A which needs B

Something like:
```toml
always_include_sets = [ 
    ["X"],
    ["A"]
]
skip_feature_sets = [
    ["X", "A"]
]

[features]
X = ["Y"]
A = ["B"]
```

Basically a starting root set of features which are selectable.
