### ISSUE TITLE
Not possible to skip the empty feature set

### ISSUE THREAD

**Issue by JSorngard** [frewsxcv/cargo-all-features#57]
Thank you so much for the extremely useful project!

I have a project that has two features, one of which must be enabled. I would therefore like to skip the empty feature set when running `cargo-test-all-features`.

I would expect the configuration option

```toml
[package.metadata.cargo-all-features]
skip_feature_sets = [
    [],
]
```

to skip the empty feature set, but instead it skips all feature sets and makes `cargo-all-features` do nothing.  
Would this be possible to change? Alternatively this is already supported and I am just missing something obvious.
